server:
  port: 8081

spring:
  banner:
    location: classpath:banner/banner-prod.txt
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  application:
    name: ms-product
  data:
    mongodb:
      uri: ${MONGODB_URI}
  output:
    ansi:
      enabled: ALWAYS
jwt:
  secret: ${SECURE_JWT}
openapi:
  info:
    github:
      url: https://github.com/josephmn/ms-customer.git
    terms: http://swagger.io/terms/
    contact:
      name: Joseph Carlos Magallanes Nolazco
      email: josephcarlos.jcmn@gmail.com
      url: https://www.linkedin.com/in/joseph-magallanes-nolazco/
    servers:
      url: http://localhost:8081
      description: Local server Swagger

springdoc:
  swagger-ui:
    #    enabled: true
    path: index.html
#logging:
#  level:
#    root: WARN
#    com.nttdata.customer: DEBUG